package com.acoudiet.app.audio

import com.acoudiet.app.config.FeatureConfig
import kotlin.math.abs
import kotlin.math.exp
import kotlin.math.ln
import kotlin.math.log10
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.roundToInt

/**
 * P-03 stage 3 (SPEC-P-03, ADR-56): time-domain transient-preserving noise gate.
 *
 * This is the Kotlin twin of `ai/src/denoise_td.py`, which is the specification. The two must agree
 * element-wise; `NoiseGateParityTest` asserts that against a golden vector produced by the Python
 * reference, and the golden vector is regenerated by
 * `python tool/gen_noise_gate_golden.py`.
 *
 * ### Why this algorithm, and why it replaced the first generation
 *
 * `ADR-52`/`ADR-53` measured the spectral family (per-bin subtraction, with and without a spectral
 * floor) on the frozen `test_mobile` split with real noise mixed in, and **every** configuration
 * either removed no noise or removed the signal with it. The cause is structural: the six classes
 * are separated by **broadband transients** (crunchiness), and a per-bin gain driven by a noise
 * floor necessarily attenuates the low-energy parts of a transient -- its onset and decay, which is
 * exactly where "crunch" lives. The first generation was worse than useless: on a **noise-only**
 * patch it *increased* the energy by 9.5 dB.
 *
 * This gate applies **one broadband gain per instant**, so:
 *  * a transient's **spectrum** is untouched (no per-bin decision can chatter, so musical noise is
 *    impossible);
 *  * it can only attenuate (`gain <= 1`), so it can never invent energy;
 *  * the gain is driven by a **peak-held envelope over a look-ahead window**, so the gate is already
 *    open *before* an onset. A naive gate clips onsets; this one cannot.
 *
 * Measured (Python reference, `ai/reports/denoise_effect.md`): **-16.20 dB** on noise-only input for
 * **-1.86 dB** on clean input, and the recogniser's top1 on a noise-mixed split goes 0.1215 -> 0.2014.
 * The behaviour metrics stay inside their frozen budget (chew-count MAE 5.6% against the 25% degrade
 * line of `FF-21g`).
 *
 * ### Default OFF
 *
 * `SPEC-P-03` section 1.3 / section 5 freeze the switch at `false`, and section 2.4 forbids a silent
 * downgrade. The parameters are read from the SSOT block `denoise`; if the caller asks for the gate
 * while the parameters are missing, that is `ACD-CFG-001` -- never a quiet "off".
 *
 * ### Stateless
 *
 * No mutable state anywhere (SPEC-P-03 acceptance 6), so it stays callable from any thread. The
 * look-ahead is symmetric and therefore "non-causal", which is legitimate here: a patch is processed
 * offline, so the future samples are already in hand.
 */
object NoiseGate {

    /** 1e-12, the floor that keeps `log10` and the divisions finite -- mirrors the Python reference. */
    private const val EPS = 1e-12

    private const val EPS_ENVELOPE = 1e-20

    /** Resolved parameters. Read from the generated constants; no numeric literal lives here. */
    class Params(
        val frameMs: Double = FeatureConfig.DENOISE_GATE_FRAME_MS,
        val noiseWindowMs: Double = FeatureConfig.DENOISE_GATE_NOISE_WINDOW_MS,
        val noiseBias: Double = FeatureConfig.DENOISE_GATE_NOISE_BIAS,
        val thresholdDb: Double = FeatureConfig.DENOISE_GATE_THRESHOLD_DB,
        val kneeDb: Double = FeatureConfig.DENOISE_GATE_KNEE_DB,
        val maxAttenuationDb: Double = FeatureConfig.DENOISE_GATE_MAX_ATTENUATION_DB,
        val lookaheadFrames: Int = FeatureConfig.DENOISE_GATE_LOOKAHEAD_FRAMES,
        val attackMs: Double = FeatureConfig.DENOISE_GATE_ATTACK_MS,
        val releaseMs: Double = FeatureConfig.DENOISE_GATE_RELEASE_MS,
    ) {
        /** Frame step in samples (the framing is non-overlapping: length == hop). */
        fun step(sampleRate: Int): Int =
            max(1, (sampleRate * frameMs / 1000.0).roundToInt())

        /** Minimum-statistics window, in frames. */
        fun noiseWindowFrames(): Int = max(1, (noiseWindowMs / frameMs).roundToInt())
    }

    /**
     * Applies the gate. [x] holds one patch in roughly `[-1, 1]`; the result is the same length.
     *
     * @param out optional caller-owned buffer (must be at least `length` long) to avoid an
     *        allocation on the audio path; a new array is returned when it is null or too small.
     */
    @JvmStatic
    @JvmOverloads
    fun apply(
        x: FloatArray,
        length: Int = x.size,
        params: Params = Params(),
        sampleRate: Int = FeatureConfig.SAMPLE_RATE,
        out: FloatArray? = null,
    ): FloatArray {
        val dst = if (out != null && out.size >= length) out else FloatArray(length)
        if (length < 4) {
            System.arraycopy(x, 0, dst, 0, length)
            return dst
        }

        val step = params.step(sampleRate)
        if (step <= 0) {
            System.arraycopy(x, 0, dst, 0, length)
            return dst
        }

        // --- 1. frame RMS envelope (non-overlapping frames; the tail is dropped) ----------------
        val frames = length / step
        val e = DoubleArray(if (frames == 0) 1 else frames)
        if (frames == 0) {
            var acc = 0.0
            for (i in 0 until length) {
                val v = x[i].toDouble()
                acc += v * v
            }
            e[0] = Math.sqrt(acc / length + EPS_ENVELOPE)
        } else {
            for (f in 0 until frames) {
                var acc = 0.0
                val base = f * step
                for (i in 0 until step) {
                    val v = x[base + i].toDouble()
                    acc += v * v
                }
                e[f] = Math.sqrt(acc / step + EPS_ENVELOPE)
            }
        }

        // --- 2. noise floor by minimum statistics (centred window, edge-extended) --------------
        val win = params.noiseWindowFrames()
        val noise = if (win <= 1) {
            DoubleArray(e.size) { e[it] * params.noiseBias }
        } else {
            val lo = win / 2
            val m = slidingMin(e, lo, win - 1 - lo)
            DoubleArray(m.size) { m[it] * params.noiseBias }
        }

        // --- 3. peak-hold the envelope so the gate opens BEFORE a transient --------------------
        val ePeak = if (params.lookaheadFrames <= 0) e
        else slidingMax(e, params.lookaheadFrames, params.lookaheadFrames)

        // --- 4. soft downward expansion, in dB relative to the threshold -----------------------
        val thrScale = 10.0.pow(params.thresholdDb / 20.0)
        val knee = max(params.kneeDb, 1e-6)
        val gDb = DoubleArray(ePeak.size)
        for (f in gDb.indices) {
            val thr = max(noise[f] * thrScale, EPS)
            val ratio = max(ePeak[f] / thr, EPS)
            val overDb = 20.0 * log10(ratio)
            val excess = max(-overDb, 0.0)
            val g = -params.maxAttenuationDb * (1.0 - exp(-excess / knee))
            gDb[f] = min(g, 0.0)
        }

        // --- 5. attack / release one-pole smoother (dB domain) --------------------------------
        val aAtt = exp(-params.frameMs / max(params.attackMs, 1e-6))
        val aRel = exp(-params.frameMs / max(params.releaseMs, 1e-6))
        var prev = 0.0
        for (f in gDb.indices) {
            val target = gDb[f]
            val a = if (target > prev) aAtt else aRel
            prev = a * prev + (1.0 - a) * target
            gDb[f] = prev
        }

        // --- 6. interpolate the frame-rate gain to per-sample and apply ------------------------
        // Linear interpolation between frame CENTRES, clamped outside the range -- this is exactly
        // what `numpy.interp` does when given x outside `xp`. Interpolating (rather than holding each
        // frame's gain) is what keeps the gain curve continuous and the output click-free.
        val centreOffset = (step - 1) / 2.0
        if (gDb.size == 1) {
            val g = 10.0.pow(gDb[0] / 20.0)
            for (i in 0 until length) dst[i] = (x[i] * g).toFloat()
            return dst
        }
        for (i in 0 until length) {
            val pos = (i - centreOffset) / step
            val gi = gainAt(gDb, pos, length)
            dst[i] = (x[i] * gi).toFloat()
        }
        return dst
    }

    /**
     * Linear interpolation of the frame-rate gain at fractional frame index [pos], clamped to the
     * endpoints outside the range (the documented `numpy.interp` behaviour).
     *
     * @param gainDb gains in dB, one per frame
     * @param pos fractional frame index, `(sample - centreOffset) / step`
     */
    private fun gainAt(gainDb: DoubleArray, pos: Double, @Suppress("UNUSED_PARAMETER") unused: Int): Double {
        val n = gainDb.size
        if (pos <= 0.0) return 10.0.pow(gainDb[0] / 20.0)
        if (pos >= (n - 1).toDouble()) return 10.0.pow(gainDb[n - 1] / 20.0)
        val i0 = pos.toInt()
        val frac = pos - i0
        val db = gainDb[i0] * (1.0 - frac) + gainDb[i0 + 1] * frac
        return 10.0.pow(db / 20.0)
    }

    /** Minimum over the clamped window `[i-lo, i+hi]`; edge values extend past the ends. */
    @JvmStatic
    fun slidingMin(e: DoubleArray, lo: Int, hi: Int): DoubleArray {
        val out = e.copyOf()
        for (d in -lo..hi) {
            if (d == 0) continue
            for (i in out.indices) {
                val v = e[clampIndex(i + d, e.size)]
                if (v < out[i]) out[i] = v
            }
        }
        return out
    }

    /** Maximum over the clamped window `[i-lo, i+hi]`; edge values extend past the ends. */
    @JvmStatic
    fun slidingMax(e: DoubleArray, lo: Int, hi: Int): DoubleArray {
        val out = e.copyOf()
        for (d in -lo..hi) {
            if (d == 0) continue
            for (i in out.indices) {
                val v = e[clampIndex(i + d, e.size)]
                if (v > out[i]) out[i] = v
            }
        }
        return out
    }

    private fun clampIndex(i: Int, n: Int): Int = when {
        i < 0 -> 0
        i >= n -> n - 1
        else -> i
    }

    /**
     * Energy this gate removes from a **noise-only** patch, in dB (negative = removed).
     *
     * Kept in the production object rather than in a test helper because it is the honest reading of
     * "how much noise did we remove": a gain-only stage cannot game it by damaging the signal, since
     * there is no signal. `ADR-53` used it to show the first generation *added* 9.5 dB.
     */
    @JvmStatic
    @JvmOverloads
    fun attenuationDb(noiseOnly: FloatArray, params: Params = Params()): Double {
        val out = apply(noiseOnly, params = params)
        var a = 0.0
        var b = 0.0
        for (i in noiseOnly.indices) {
            val v = noiseOnly[i].toDouble()
            val w = out[i].toDouble()
            a += v * v
            b += w * w
        }
        val r0 = Math.sqrt(a / noiseOnly.size + EPS_ENVELOPE)
        val r1 = Math.sqrt(b / out.size + EPS_ENVELOPE)
        return 20.0 * (ln(r1) - ln(r0)) / ln(10.0)
    }

    /** Absolute difference helper used by the parity test to keep its own arithmetic honest. */
    @JvmStatic
    fun maxAbsDiff(a: FloatArray, b: FloatArray): Double {
        var worst = 0.0
        for (i in 0 until min(a.size, b.size)) {
            val d = abs(a[i].toDouble() - b[i].toDouble())
            if (d > worst) worst = d
        }
        return worst
    }
}
